### ISSUE TITLE
Support Cachet

### ISSUE THREAD

**Issue by jbrooksuk** [sahin/status-page#1]
[Cachet](https://cachethq.io) powers a fair few status pages these days. Let's add support for it.

**Comment by jbrooksuk** [comment]
I noticed that both the StatusPage.io and Status.io Parsers are currently scraping the page content. Why not rely on the API?

**Comment by sahin** [comment]
@jbrooksuk I built this as weekend project , I didnt aware the there were apis, can you share the public apis for the StatusPage.io and Status.io. 

I will also do the cachet , it is in the serviceswillbeadd

**Comment by sahin** [comment]
@jbrooksuk where can I find the list of startups who are using Cachet

**Comment by jbrooksuk** [comment]
> can you share the public apis for the StatusPage.io and Status.io.

http://doers.statuspage.io/ and http://docs.statusio.apiary.io/

> where can I find the list of startups who are using Cachet

I'm afraid that you can't. You'll just have to stumble across them or ask for people who do.

**Comment by sahin** [comment]
hmm @jbrooksuk  

for status page 
"Each IP address is limited to 1 request / second as measured on a 60 second rolling window. To get this limit increased or lifted, please contact hi@statuspage.io."

and I have a feeling that you can only get your own data not others.
http://doers.statuspage.io/api/v1/page_profile/ It say "get your page"

I will check  statusio
